# Programming speed must be reduced otherwise the
# switch will will exit the flashing routine
# Use:
# esphome run tuya_plug.yaml --upload_speed 19200
esphome:
  comment: "Tuya Smart Socket EU 20A with Power Monitor"
  #Testdevice
  #name: tuya-smartplug-f1d4ba
  #name_add_mac_suffix: false
  name: tuya-smartplug
  name_add_mac_suffix: true
  
  on_boot:
    then:
      - lambda: |-
          if (!id(wifi_connected)) {
            id(ap_mode_blink).execute();
          }  

bk72xx:
  board: generic-bk7231n-qfn32-tuya # actually a T34 Tuya module

logger:
    level: NONE
    
wifi:
  # In case a secrets.yaml file is available in the root folder
  # with the following content:
  # secrets.yaml
  # wifi_ssid: "SSID"
  # wifi_password: "PASSWORD"
  
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  
  ap:
    ssid: "TuyaPlug"
    
  on_connect:
    - script.stop: ap_mode_blink
    - output.turn_on: led_output
    
captive_portal:

api: 
    reboot_timeout: 600min

ota:
  platform: esphome
  
web_server:
  version: 3
  port: 80  


  
# Make LED controllable as a light
output:
  - platform: gpio
    pin: P14
    id: relay_1
  - platform: gpio
    pin:
      number: P24
      inverted: false
    id: led_output

# uncomment this part if you want to control the LED by Homeassistant
#light:
#  - platform: binary
#    name: "Status LED"  # blue LED
#    id: status_light
#    output: led_output
#    internal: true  # hide from Home Assistant unless needed   

# Local button on PCB
binary_sensor:
  - platform: gpio
    id: button_1        # illuminated button
    pin:
      number: P26
      mode: INPUT_PULLUP
      inverted: true  
    filters:
      - delayed_on: 50ms
    on_press:
      - switch.toggle: relay_switch  # manual control for relay
      
# Switch to control the relay from the UI
switch:
  - platform: output
    name: "Relay"
    id: relay_switch
    output: relay_1
    
uart:
  id: bl0942_uart  # UART1 is used to read the data from the BL0942
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 4800    

# Belling BL0942 Energy Monitor
sensor:
  - platform: bl0942
    uart_id: bl0942_uart
    line_frequency: 50Hz
    voltage:
      name: 'Voltage'
    current:
      name: 'Current'
    power:
      name: 'Power'
    energy:
      name: 'Energy'
    frequency:
      name: "Frequency"
      
  - platform: wifi_signal
    name: "TuyaPlug WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s        
    
script:
  - id: ap_mode_blink
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return !id(wifi_connected);'
          then:
            - output.turn_on: led_output
            - delay: 200ms
            - output.turn_off: led_output
            - delay: 1000ms     

globals:
  - id: wifi_connected
    type: bool
    restore_value: no
    initial_value: 'false'
    