# Programming speed must be reduced otherwise the
# switch will will exit the flashing routine
# Use:
# esphome run tuya_plug.yaml --upload_speed 19200
esphome:
  comment: "Tuya Smart Socket EU 20A with Power Monitor"
  #Testdevice
  name: tuya-smartplug-f23988
  name_add_mac_suffix: false
  #name: tuya-smartplug
  #name_add_mac_suffix: true
  
  on_boot:
    then:
      - lambda: |-
          if (!id(wifi_connected)) {
            id(ap_mode_blink).execute();
          }  

bk72xx:
  board: generic-bk7231n-qfn32-tuya # actually a T34 Tuya module

logger:
    level: NONE
    
wifi:
  # In case a secrets.yaml file is available in the root folder
  # with the following content:
  # secrets.yaml
  # wifi_ssid: "SSID"
  # wifi_password: "PASSWORD"
  
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  
  ap:
    ssid: "TuyaPlug"
    
  on_connect:
    - script.stop: ap_mode_blink
    - lambda: |-
        id(wifi_connected) = true;
        if (id(relay_switch).state) {
          // Relay is ON - turn LED OFF
          id(led_output).set_level(0.0);
        } else {
          // Relay is OFF - start pulsing
          id(relay_off_pulse).execute();
        }
    
  on_disconnect:
    - lambda: |-
        id(wifi_connected) = false;
        
captive_portal:

api: 
    reboot_timeout: 600min

ota:
  platform: esphome
  
web_server:
  version: 3
  port: 80  


  
# Make LED controllable with PWM for pulsing effect
output:
  - platform: gpio
    pin: P14
    id: relay_1
  - platform: libretiny_pwm
    pin:
      number: P24
      inverted: false
    id: led_output
    frequency: 1000Hz

# Local button on PCB
binary_sensor:
  - platform: gpio
    id: button_1        # illuminated button
    pin:
      number: P26
      mode: INPUT_PULLUP
      inverted: true  
    filters:
      - delayed_on: 50ms
    on_multi_click:
      # Short press - toggle relay (normal operation)
      - timing:
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - switch.toggle: relay_switch
      
      # Long press (10 seconds) - factory reset with warning blink
      - timing:
          - ON for at least 10s
        then:
          - logger.log: "Factory reset triggered - button held for 10 seconds!"
          - script.execute: factory_reset_warning
      
# Switch to control the relay from the UI
switch:
  - platform: output
    name: "Relay"
    id: relay_switch
    output: relay_1
    on_turn_on:
      - script.stop: relay_off_pulse
      - if:
          condition:
            lambda: 'return id(wifi_connected);'
          then:
            # Relay ON - turn LED OFF
            - output.set_level:
                id: led_output
                level: 0%
          else:
            # Not connected - keep AP mode blink running
            - script.execute: ap_mode_blink
    on_turn_off:
      - if:
          condition:
            lambda: 'return id(wifi_connected);'
          then:
            # Relay OFF - start pulsing
            - script.execute: relay_off_pulse
          else:
            # Not connected - keep AP mode blink running
            - script.execute: ap_mode_blink

# Factory reset button (can also be triggered via API/web interface)
button:
  - platform: factory_reset
    name: "Factory Reset"
    id: factory_reset_button
    internal: true
    
uart:
  id: bl0942_uart  # UART1 is used to read the data from the BL0942
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 4800    

# Belling BL0942 Energy Monitor
sensor:
  # Status sensor for connectivity checking - creates /sensor/status endpoint
  - platform: template
    name: "Status"
    id: status_sensor
    lambda: 'return 1.0;'  # Always returns 1 when device is online
    update_interval: 60s
    internal: true  # Exposed to web server

  - platform: bl0942
    uart_id: bl0942_uart
    line_frequency: 50Hz
    voltage:
      name: 'Voltage'
    current:
      name: 'Current'
    power:
      name: 'Power'
      filters:
        - multiply: -1
    energy:
      name: 'Energy'
    frequency:
      name: "Frequency"
    update_interval: 10s 
      
  - platform: wifi_signal
    name: "TuyaPlug WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s        
    
script:
  # AP mode / disconnected - fast blink
  - id: ap_mode_blink
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return !id(wifi_connected);'
          then:
            - output.turn_on: led_output
            - delay: 200ms
            - output.turn_off: led_output
            - delay: 1000ms
            
  # Relay OFF - slow breathing pulse
  - id: relay_off_pulse
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return !id(relay_switch).state && id(wifi_connected);'
          then:
            # Fade in from 10% to 100% over 1.5 seconds
            - output.set_level:
                id: led_output
                level: 10%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 20%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 30%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 40%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 50%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 60%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 70%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 80%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 90%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 100%
            - delay: 150ms
            # Fade out from 100% to 10% over 1.5 seconds
            - output.set_level:
                id: led_output
                level: 90%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 80%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 70%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 60%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 50%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 40%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 30%
            - delay: 150ms
            - output.set_level:
                id: led_output
                level: 20%
            - delay: 150ms

  # Factory reset warning - rapid blink before reset
  - id: factory_reset_warning
    mode: restart
    then:
      - script.stop: ap_mode_blink
      - script.stop: relay_off_pulse
      # Rapid blink 5 times as warning
      - repeat:
          count: 5
          then:
            - output.turn_on: led_output
            - delay: 100ms
            - output.turn_off: led_output
            - delay: 100ms
      # Execute factory reset
      - button.press: factory_reset_button

globals:
  - id: wifi_connected
    type: bool
    restore_value: no
    initial_value: 'false'

